apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "gobehost-operator.fullname" . }}-manager-role
  labels:
    {{- include "gobehost-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - games.gobehost.com
  resources:
  - gameservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - games.gobehost.com
  resources:
  - gameservers/finalizers
  verbs:
  - update
- apiGroups:
  - games.gobehost.com
  resources:
  - gameservers/status
  verbs:
  - get
  - patch
  - update