apiVersion: v1
kind: Service
metadata:
  name: {{ include "gobehost-operator.fullname" . }}-webhook-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gobehost-operator.labels" . | nindent 4 }}
spec:
  ports:
    - port: 443
      targetPort: webhook
      protocol: TCP
      name: https
  selector:
    control-plane: controller-manager
    {{- include "gobehost-operator.selectorLabels" . | nindent 4 }}