---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-games-gobehost-com-v1alpha1-gameserver
  failurePolicy: Fail
  name: mgameserver-v1alpha1.kb.io
  rules:
  - apiGroups:
    - games.gobehost.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - gameservers
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-games-gobehost-com-v1alpha1-gameserverfleet
  failurePolicy: Fail
  name: mgameserverfleet-v1alpha1.kb.io
  rules:
  - apiGroups:
    - games.gobehost.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - gameserverfleets
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-games-gobehost-com-v1alpha1-gameserver
  failurePolicy: Fail
  name: vgameserver-v1alpha1.kb.io
  rules:
  - apiGroups:
    - games.gobehost.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - gameservers
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-games-gobehost-com-v1alpha1-gameserverfleet
  failurePolicy: Fail
  name: vgameserverfleet-v1alpha1.kb.io
  rules:
  - apiGroups:
    - games.gobehost.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - gameserverfleets
  sideEffects: None
