replicaCount: 1

image:
  repository: linusdb/gobehost
  pullPolicy: IfNotPresent
  tag: "v0.3.1"

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 64Mi

nodeSelector: {}

tolerations: []

affinity: {}

manager:
  metrics:
    bindAddress: "0"
  healthProbe:
    bindAddress: ":8081"
  webhook:
    port: 9443

certmanager:
  enabled: true

backup:
  enabled: false
  s3:
    endpoint: ""
    bucket: ""
    pathPrefix: "backups"
    secretName: "gobehost-backup-s3-creds"
    accessKey: ""
    secretKey: ""